name: Generate files

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  generate-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Generate syukujitsu.json
        run: |
          output=$(
            curl -s -A "https://github.com/woxtu/syukujitsu-json" https://www8.cao.go.jp/chosei/shukujitsu/syukujitsu.csv \
              | iconv -f sjis -t utf-8 \
              | node scripts/generate.js
          ) && echo "$output" > syukujitsu.json
      - name: Push generated files
        run: |
          git config user.name github-actions
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          if git commit -m "Generate files by GitHub Actions"; then
            git push
            git tag "$(TZ=JST-9 date +"v%Y.%m.%d")"
            git push --tags
          fi
